[toolchain]
channel = "stable"
components = [ "rust-src", "llvm-tools-preview", "rustfmt", "clippy" ]
targets = [
  "aarch64-unknown-none-softfloat",
  "armv7r-none-eabi",
  "powerpc64-unknown-linux-gnu",
  "powerpc64le-unknown-linux-gnu",
  "riscv32imc-unknown-none-elf",
  "riscv64imac-unknown-none-elf",
  "riscv64gc-unknown-none-elf",
]
