[toolchain]
channel = "nightly-2023-03-03"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets = [
  "aarch64-unknown-none-softfloat",
  "armv7a-none-eabi",
  "powerpc64-unknown-linux-gnu",
  "powerpc64le-unknown-linux-gnu",
  "riscv32imac-unknown-none-elf",
  "riscv64imac-unknown-none-elf",
]
