[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
clap-verbosity-flag = "1.0"
log = "0.4"
env_logger = "0.9"
ctrlc = "3.2"
byteorder = "1"
pathdiff = "0.2"
