[package]
name = "hifive"
version = "0.1.0"
authors = ["Ronald G. Minnich <rminnich@gmail.com>"]
edition = "2018"

[dependencies]
console = { path = "../../../console" }
payloads = { path = "../../../../payloads"}
architecture = { path = "../../../arch/riscv/rv64"}
device_tree = { path = "../../../lib/device_tree" }
soc = { path = "../../../soc" }
register = "0.3.2"
static-ref = "0.1.1"

[dependencies.drivers]
path = "../../../drivers/uart"
features = ["sifive"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
