[package]
name = "sbi"
version = "0.1.0"
authors = ["oreboot authors"]
edition = "2021"

[dependencies]
nb = "1"
rustsbi = "0.2.2"
bitflags = "1"
buddy_system_allocator = "0.8"
lazy_static = { version = "1", features = ["spin_no_std"] }
riscv = { version = "0.7.0", features = ["inline-asm"] }
embedded-hal = "0.2.6"
vcell = "0.1.3"
r0 = "1.0"
