[package]
name = "oreboot-k230-bt0"
version = "0.1.0"
authors = ["oreboot authors"]
edition = "2021"

[dependencies]
embedded-hal = "=1.0.0"
embedded-hal-nb = "=1.0.0"
nb = "1"
spin = "0.9"

riscv = { version = "=0.12.1", features = ["critical-section-single-hart"] }

log = { path = "../../../../lib/log" }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
util = { path = "../../../../lib/util" }

[features]
default = []
