[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/x86_64-unknown-none/debug"
RUST_TARGET_PATH = "${OREBOOT}/src/cpu/intel/q35"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/x86_64-unknown-none/release"
RUST_TARGET_PATH = "${OREBOOT}/src/cpu/intel/q35"

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.default]
dependencies = [ "bootblob" ]
script = [
	"dtc fixed-dtfs.dts -O dtb -o fixed-dtfs.dtb",
	"layoutflash fixed-dtfs.dtb ${TARGET_DIR}/oreboot.bin",
	"dd if=payloadA of=${TARGET_DIR}/oreboot.bin conv=notrunc"
]

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/oreboot", "${TARGET_DIR}/bootblob.bin"]

[tasks.run]
dependencies = ["default"]
command = "qemu-system-x86_64"
args = ["-m", "1g", "-machine", "q35", "-nographic", "-bios", "${TARGET_DIR}/oreboot.bin", "-s","-cpu", "Icelake-Server", "-monitor", "/dev/tty",]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/oreboot"]
