[config]
# no default tasks
skip_core_tasks = true

[env.development]
CARGO_ARGS = "--verbose"
TARGET_DIR = "target/x86_64-unknown-none/debug"

[env.release]
CARGO_ARGS = "--release --verbose"
TARGET_DIR = "target/x86_64-unknown-none/release"

[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.default]
dependencies = [ "bootblob" ]

[tasks.build]
dependencies = [ "install-rust-src" ]
toolchain = "nightly"
command = "cargo"
args = ["xbuild", "@@split(CARGO_ARGS, )"]

[tasks.bootblob]
dependencies = [ "build" ]
command = "cargo"
args = ["objcopy", "--", "-O", "binary", "${TARGET_DIR}/oreboot", "${TARGET_DIR}/bootblob.bin"]

[tasks.resizeblob]
dependencies = [ "bootblob" ]
command = "qemu-img"
args = ["resize", "${TARGET_DIR}/bootblob.bin", "33554432"]

[tasks.run]
dependencies = ["resizeblob"]
command = "qemu-system-x86_64"
args = ["-m", "1g", "-machine", "q35", "-nographic", "-bios", "none", "-pflash", "${TARGET_DIR}/bootblob.bin"]

[tasks.objdump]
dependencies = ["build"]
command = "cargo"
args = ["objdump", "--", "-d", "${TARGET_DIR}/oreboot"]
