[package]
name = "cpu"
version = "0.1.0"
authors = ["Oreboot Authors"]
edition = "2018"

[dependencies]
arch = { path = "../../../arch/arm64/armv8"}

[profile.release]
opt-level = 'z'  # Optimize for size.
