[package]
name = "oreboot-nezha-main"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1"
embedded-hal = "=1.0.0"
embedded-hal-nb = "=1.0.0"
lazy_static = { version = "1", features = ["spin_no_std"] }
miniz_oxide = { version = "=0.8.5", default-features = false }
nb = "1"
riscv = { version = "=0.12.1", features = ["critical-section-single-hart"] }
rustsbi = { version = "=0.4.0", features = ["machine"] }
sbi-spec = "0.0.4"
spin = "0.9"
vcell = "0.1.3"

log = { path = "../../../../lib/log" }
oreboot-arch = { path = "../../../../arch", features = ["riscv64"] }
oreboot-soc = { path = "../../../../soc", features = ["sunxi_d1"] }
util = { path = "../../../../lib/util" }

[features]
default = []
supervisor = []
